### PR TITLE
Added dup command; added tooltips, directory listing, and reindexing to CGI 

### PR DESCRIPTION
**Pull request by digitalman2112**
Features & Fixes

CGI: Fixed double-free issue reported in apache error logs (possibly related: https://github.com/zevv/duc/issues/46)
CGI: Added optional (-i) directory listing below graph 
CGI: Added optional (-l) reindexing link / process in report table
CGI: Added jQuery + tooltipster tooltips with JSON support in CGI (https://github.com/zevv/duc/issues/42)
CGI: Added option (-p) to set size of chart in pixels
CGI: Added option (-m) to set max levels in chart
CGI: Changed coordinate lookup calls to return an immediate redirect to the full path so that the correct path is always showing in the browser url 
CGI: Created www directory to hold new js / css to support the tooltips. Please note that there are required dependencies on https://github.com/iamceege/tooltipster; specifically jquery.tooltipster.min.js and tooltipster.css which are now included by the duc CGI.

Quick view of new CGI: https://www.youtube.com/watch?v=kLRY8iviIMA

DUP: Added new dup command from a fork of xml command
DUP: Supports matching by name and size (default), extension and size (-e), size (-s), name (-n), and string comparisons can be made case insensitive (-i)
DUP: Duplicate scan can be set for files (default) or for folders (-f)
DUP: Duplicate scan can be constrained to a minimum file size in megabytes (-m)
DUP: Matching candidates are returned as rows, with a summary below.

Related Docker container for my fork of DUC: https://registry.hub.docker.com/u/digitalman2112/duc/
I've created this container so that DUC can be installed as an extension for unRAID server: http://lime-technology.com/forum/index.php?topic=37556

I still want to integrate the DUP functionality into the CGI, and spend more time testing and looking for memory leaks (My C is rusty and this is my first time with jQuery) - but I wanted to start the process of sharing my changes. I'm open to any & all feedback, I reworked quite a few things as I learned more about the project and its many function calls. I purposely tried to limit my changes to a few files - and so there could be some optimizations if you want to merge.

Thanks for creating such a great project!

### CODE REVIEW

**Comment by zevv** [comment]
Hi Ian,

Thanks for the work, nice features, I love the tooltips!. 

A few comments:

-  This is one huge merge to pull in one go, so I'd like to split this up into a few smaller pieces. Would it be possible to split into a few separate patches for the various CGI features and the dup command?

- If I understand right the  CGI will need to have a few static files (the .css and .js's) available to work, so it's no longer possible to run the CGI standalone with a relative simple web server setup. The URLs where the CGI generated HTML loads the js and CSS from is not configurable, so these files will have to go in the document root at all times. I'm not sure if this will work for most people. Could we have the CGI serve these files instead, either inline in the HTML or on a separate request with something like 'cmd=css'?

- I'm not sure if the 'dup' feature is something that should be in Duc. There's a lot of tools available for identifying duplicates in a directory tree, and I feel that proper duplicate finding should be able to check by content/hash as well, and not just size and/or name. 

Thanks,

**Comment by digitalman2112** [comment]
>Thanks for the work, nice features, I love the tooltips!.

Thanks for the fast response - I spent the time on the tooltips since I saw you post about the desire to have them and it was my way of saying thank you for your work creating DUC.

>This is one huge merge to pull in one go, so I'd like to split this up into a few smaller pieces. Would it be possible to split into a few separate patches for the various CGI features and the dup command?

I'm happy to split as needed in order to help things get merged. **Let's focus on merging the new cgi features and I'll make the case for dup in a subsequent comment.**

* I didn't change any core files, and there is no dependencies at this time between cgi.c and dup.c, so at the moment, you could pull in just cgi.c and the www files with no issues relating to not merging dup.c
* The makefile changes are NOT required to merge cgi.c
* The www files are only required with the CGI tooltip addition. I did not make any changes to the makefile to deal with the www directory since the www files simply need to be copied to a web server dir by the end user.

>If I understand right the CGI will need to have a few static files (the .css and .js's) available to work, so it's no longer possible to run the CGI standalone with a relative simple web server setup. The URLs where the CGI generated HTML loads the js and CSS from is not configurable, so these files will have to go in the document root at all times. I'm not sure if this will work for most people. Could we have the CGI serve these files instead, either inline in the HTML or on a separate request with something like 'cmd=css'?

* I can make the tooltips a command line option for cgi.c as I did with the dir listing, the reindex option, the graph size and the maxlevels. They could be off by default since they require the extra setup. Very easy to do and it lets people that want to run standalone do so while allowing others to benefit from tooltips.  
* The duc.js and tooltipster-duc.js **could** be served by the CGI, but then you have to rebuild the project in order to change the CSS - and to edit / work on your JS is a lot more work. (I'm assuming at some point you'll want to get to a package and not require every user to build from source, but maybe this is not in the plan...)
* The other two required files are MIT licensed from tooltipster - I chose to NOT include them in the repo since you'd need to update your project over time as they change. You may want to handle that differently. 
* Someone far more experienced than me might be able to do the tooltips with pure JS and no jQuery + tooltipster - but they'd also have the fun of dealing with cross-browser issues that libraries like jQuery handle for you.
* I'd be happy to write mod the install instructions for CGI to include dealing with the new files if that would help. I could also do a full blog tutorial on duc + apache2 configuration if that would be helpful since I have it automated for my docker build, I have the steps already documented.

Next steps for me (hopefully today):
* Add the command line option for tooltips for those that need to run standalone (no external js dependencies)
* Test a build without dup.c and the makefile change to validate that you can merge cgi.c and the www files without any issues.

Thoughts?

**Comment by digitalman2112** [comment]
Also, if it would make it easier for you (not sure how the merging works), I can create a new fork that has JUST the CGI changes and do a pull request new fork so that you aren't sorting through all these commits. I won't do that unless you agree, again because I'm not sure of what is easiest for you.

**Comment by zevv** [comment]
* On 2015-01-10 17:36:27 +0100, Ian Cole wrote:
 
> Also, if it would make it easier for you (not sure how the merging
> works), I can create a new fork that has JUST the CGI changes and do a
> pull request new fork so that you aren't sorting through all these
> commits. I won't do that unless you agree, again because I'm not sure
> of what is easiest for you.

It would not be too hard for me to just manually merge the cgi only, but
it will mess up the git history a bit; in this case the code will look
as if it was authored by me and not coming from your branch. 
 

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
* On 2015-01-10 17:17:12 +0100, Ian Cole wrote:
 
> Thanks for the fast response - I spent the time on the tooltips since
> I saw you post about the desire to have them and it was my way of
> saying thank you for your work creating DUC.

Great initiative, much appreciated! :)

> * The www files are only required with the CGI tooltip addition. I did
> not make any changes to the makefile to deal with the www directory
> since the www files simply need to be copied to a web server dir by
> the end user.

Separate www files is not really a problem, and more people have
requested this in the past to make it easier to edit style sheets etc.
My only critique is that the documents are referenced by an absolute
path by the CGI, and *must* be in the HTTP document root at this time.
I guess we could add a CGI command line argument specifying the HTTP
root for the static docs.

(There's a lot of command line options already, maybe it is time to
switch to a config file)

> * The duc.js and tooltipster-duc.js **could** be served by the CGI,
> but then you have to rebuild the project in order to change the CSS -
> and to edit / work on your JS is a lot more work.

That's not nice, true. Separate files would be the way to go, albeit
this complicates installation a bit.

> (I'm assuming at some point you'll want to get to a package and not
> require every user to build from source, but maybe this is not in the
> plan...) 

Packaging is a tedious job, mostly because of the pleora of different
package formats (deb, rpm, tgz) and all the different flavours and
versions of unixes/linuxes. Personally I'd like to go no further then
'make install', and leave the packaging to package maintainers who
actually *do* know how to do this stuff.

> Next steps for me (hopefully today): * Add the command line option for
> tooltips for those that need to run standalone (no external js
> dependencies) * Test a build without dup.c and the makefile change to
> validate that you can merge cgi.c and the www files without any
> issues.

That would be just fine. Having the feature as a separate merge is
definately better. Could you add the basic installation instructions
into the README in your patch as well?
 

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by digitalman2112** [comment]
>It would not be too hard for me to just manually merge the cgi only, but
it will mess up the git history a bit; in this case the code will look
as if it was authored by me and not coming from your branch.

I'm still learning all this - thanks for your guidance. I found [this article] (http://blog.spreedly.com/2014/06/24/merge-pull-request-considered-harmful/#.VLFexYrF_Al) which helped make some sense of it for me. Not sure if this method is cleaner on the history that the method you were thinking.

In the end, I'll do what ever process is easiest for you, I don't need credit for the changes, but I appreciate your concern about it :)

Note: the command line option for the tooltips is now in a commit - they (along with the js / css includes) are disabled by default now.

**Comment by digitalman2112** [comment]
>Separate www files is not really a problem, and more people have
requested this in the past to make it easier to edit style sheets etc.
My only critique is that the documents are referenced by an absolute
path by the CGI, and *must* be in the HTTP document root at this time.
I guess we could add a CGI command line argument specifying the HTTP
root for the static docs.
>(There's a lot of command line options already, maybe it is time to
switch to a config file)

Great point, that was a miss on my part (not making the HTTP root an option) - in the short term, I could have the root passed with the -t option to enable tooltips. Then if you want to do a config file / split out CSS overall later, -t would be updated to no longer require the path.

If you want me to implement the config file / CSS split, I can figure it out, but would like your guidance on the config file type / read method / options. In other words, lets plan together, then I'd implement.

Let me know which way you'd like to resolve (quickly mod -t to require a path, or start working on the config file).

>Could you add the basic installation instructions
into the README in your patch as well?

Will do.

**Comment by l8gravely** [comment]
>>>>> "Ian" == Ian Cole <notifications@github.com> writes:

Ian> It would not be too hard for me to just manually merge the cgi only, but
Ian> it will mess up the git history a bit; in this case the code will look
Ian> as if it was authored by me and not coming from your branch.
   
Ian> I'm still learning all this - thanks for your guidance. I found
Ian> this article which helped make some sense of it for me. Not sure
Ian> if this method is cleaner on the history that the method you were
Ian> thinking.

Me too!  I like git, but it can be a very steep learning curve.  

If you can setup seperate branches for each set of commits that can be
pulled into the main tree, that would be great, then we can all look
over the propesed changes and make comments and suggestions.  

Or just post a patch bundle, with each set of features in a group of
one or more patches.  Sorta like how proposed patches get sent to the
kernel mailing list, and when acepted either pulled in via the patch,
or by the remote git branch.  

Ian> In the end, I'll do what ever process is easiest for you, I don't
Ian> need credit for the changes, but I appreciate your concern about
Ian> it :)

No no, please take credit, it's a group effort!

Ian> Note: the command line option for the tooltips is now in a commit
Ian> - they (along with the js / css includes) are disabled by default
Ian> now.

I personally don't mind the CSS and JS at all, I think having a
standalone CGI script is honestly not the best idea any more, but
maybe it's better to move somewhere in the middle.

But I haven't had a chance to look at your patches in detail.  My
latest work has been on the file count stuff, and I've run into some
problems there which have me stumped.  Doesn't help that it's ski
season too... :-)

John

**Comment by l8gravely** [comment]
>>>>> "Ian" == Ian Cole <notifications@github.com> writes:

Ian> Separate www files is not really a problem, and more people have
Ian> requested this in the past to make it easier to edit style sheets etc.
Ian> My only critique is that the documents are referenced by an absolute
Ian> path by the CGI, and must be in the HTTP document root at this time.
Ian> I guess we could add a CGI command line argument specifying the HTTP
Ian> root for the static docs.
Ian> (There's a lot of command line options already, maybe it is time to
Ian> switch to a config file)
   
Ian> Great point, that was a miss on my part (not making the HTTP root
Ian> an option) - in the short term, I could have the root passed with
Ian> the -t option to enable tooltips. Then if you want to do a config
Ian> file / split out CSS overall later, -t would be updated to no
Ian> longer require the path.

Ian> If you want me to implement the config file / CSS split, I can
Ian> figure it out, but would like your guidance on the config file
Ian> type / read method / options. In other words, lets plan together,
Ian> then I'd implement.

Ian> Let me know which way you'd like to resolve (quickly mod -t to
Ian> require a path, or start working on the config file).

Ian> Could you add the basic installation instructions
Ian> into the README in your patch as well?
   
Just my initial comments on the CGI stuff, but I like the idea of
NOT having to pass in a bunch of config options to the CGI script
itself via the web broweser, either as hidden options to a POST
request, etc.  

We should NOT be trusting any of the input from the user, and should
instead to being pretty paranoid and fail nicely if any of the inputs
is outside the expected bounds by default.  Last thing we need is for
DUC to be a way to hack web servers, etc.

So having a seperate config file (-c cgi.conf ?) which then lists
whether we're offering JS and CSS support would be in a single place
which could be outside the webroot completely.

And of course we might want to make it so that the CGI tool can't
actually WRITE to the duc DB at all.  I see that db_open already does
the right thing, but since it does fall back to $DUC_DATABASE and then
~/.duc.db, we might want to think about requiring the cgi routines to
only open the explicitly specified DB(s).

And of course I'd love for the CGI to be able to generate an index
page listing all the DBs and their top paths in a nice list.  I have
alot of NFS filesystems I want to monitor, and I split them into
seperate DBs since they are updated on differnet schedules.  So having
a master index.cgi would be *really* nice for me.

I'm out of time right now, but I'm going to try and look over your
patches tonight if I can.

John

**Comment by digitalman2112** [comment]
John:
>If you can setup seperate branches for each set of commits that can be
pulled into the main tree, that would be great, then we can all look
over the propesed changes and make comments and suggestions.

>Or just post a patch bundle, with each set of features in a group of
one or more patches.  Sorta like how proposed patches get sent to the
kernel mailing list, and when acepted either pulled in via the patch,
or by the remote git branch.

I'll have to learn more, I don't immediately know how to do either of those. I'm not sure if any commits spanned both CGI and DUP, I'll need to sort that out. Any pointers are welcome.

John:
>Just my initial comments on the CGI stuff, but I like the idea of
NOT having to pass in a bunch of config options to the CGI script
itself via the web broweser, either as hidden options to a POST
request, etc.

For clarity, the CGI options are command line options set in the duc.cgi bash script as it calls the duc executable. 

John:
>And of course we might want to make it so that the CGI tool can't
actually WRITE to the duc DB at all. I see that db_open already does
the right thing...

When I added the ability to trigger a reindex, I open the database with write for that command, it does now call open with write capability for at least that command. I added the reindex link because I'm packaging duc to run in a docker container in such a way that they wouldn't need to go to the command line.

John:
>And of course I'd love for the CGI to be able to generate an index
page listing all the DBs and their top paths in a nice list.  I have
alot of NFS filesystems I want to monitor, and I split them into
seperate DBs since they are updated on differnet schedules.  So having
a master index.cgi would be *really* nice for me.

I also have a need for this type of multi-database hierarchy if built. (I'll explain why I think dup is a good idea after we get the CGI merged... but for now, its a big deal when consolidating archives and this multi-database concept would make it even more appealing)

John:
>I'm out of time right now, but I'm going to try and look over your
patches tonight if I can.

Thanks. If either of you want to chat interactively, I'm always on google hangouts (ian.cole@gmail.com) if near a computer (which is quite often).

**Comment by digitalman2112** [comment]
Took me a rediculously long time (I had to learn reset, branch, checkout, cherry-pick, merge, and more...)

I've created two feature branches, one for the CGI work, one for the DUP work. I reverted my master back to match this repo, and then I have a develop branch that has my two features merged together. 

When I did the reset, it automatically closed this pull request. I need to spend some time testing the CGI feature branch independently, then I'll submit a pull request for the CGI work. 

Ian

**Comment by zevv** [comment]
* On 2015-01-11 06:29:29 +0100, Ian Cole wrote:
 
> Took me a rediculously long time (I had to learn reset, branch, checkout, cherry-pick, merge, and more...)

Story of my life; git and github is all great stuff, but the learning
curver is quite steep. Things get even more complicated if you start
doing things like rebasing etc, there's no end to what one can do with
git.

> I've created two feature branches, one for the CGI work, one for the
> DUP work. 

That's great, thank you.

> I reverted my master back to match this repo, and then I have a
> develop branch that has my two features merged together. 

Sounds like the right way to go.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
Hi Ian,

I've never merged your tooltip because of the added complexity. The feature is still a nice to have, so I've created a minimal implementation using only a bit of bare bone javascript, available in the separate cgi-tooltip branch.

Let me know if this works for you.

**Comment by digitalman2112** [comment]
I understood and respected that you had a vision for the tool - and the
features within it.

I've been very heads down at work, but following along with all the recent
improvements (reading email) - thank you for continuing to improve the tool.

I'll give it a shot this weekend if I don't end up working.

Thanks!
Ian

**Pull request closed without merging**
