### PR TITLE
add db parameter to cgi

### PR DESCRIPTION
**Pull request by daduke**
we use the cgi output for many different databases. Added db parameter to the cgi so that this works.

### CODE REVIEW

**Comment by zevv** [comment]
Hi Christian,

Can you elaborate on what problem you are trying to solve with this
patch?

* On 2015-01-16 13:54:01 +0100, Christian Herzog wrote:
 
> we use the cgi output for many different databases. Added db parameter to the cgi so that this works.
> You can merge this Pull Request by running:
> 
>   git pull https://github.com/daduke/duc master
> 
> Or you can view, comment on it, or merge it online at:
> 
>   https://github.com/zevv/duc/pull/50
> 
> -- Commit Summary --
> 
>   * add db parameter to cgi
> 
> -- File Changes --
> 
>     M duc/cgi.c (7)
> 
> -- Patch Links --
> 
> https://github.com/zevv/duc/pull/50.patch
> https://github.com/zevv/duc/pull/50.diff
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/duc/pull/50

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment]
Hi Ico,

we are using cgi like so:
`#!/bin/bash

saveIFS=$IFS
IFS='=&'
parm=($QUERY_STRING)
IFS=$saveIFS

declare -A array
for ((i=0; i<${#parm[@]}; i+=2))
do
    array[${parm[i]}]=${parm[i+1]}
done

for ((i=0; i<${#parm[@]}; i+=2))
do
    declare var_${parm[i]}=${parm[i+1]}
done

/opt/duc/bin/duc cgi -d "db/$var_db.db"`

in order to create links like `/cgi-bin/index.cgi?db=foobar-304`. Without the patch, the  links duc creates do not know which database to use. I might be doing something strange here, but my patch fixes it :)

thanks,
-Christian

**Comment by zevv** [comment]
Hi,

I'm not merging this patch, sorry. 

- The char *db variable is NULL if the value not passed by the CGI.
  This breaks the printf()'s using the variable.

- Your example is not secure, since you are passing a database file name
  to duc which can be altered from the remote end by simply editing the
  url.

- It mereley passes a CGI variable around which is not used by duc
  itself, but only by the wrapper script at your setup. You could also
  solve this with cookies, without using any special support from duc
  itself.



* On 2015-01-16 14:17:58 +0100, Christian Herzog wrote:
 
> Hi Ico,
> 
> we are using cgi like so:
> `#!/bin/bash
> 
> saveIFS=$IFS
> IFS='=&'
> parm=($QUERY_STRING)
> IFS=$saveIFS
> 
> declare -A array
> for ((i=0; i<${#parm[@]}; i+=2))
> do
>     array[${parm[i]}]=${parm[i+1]}
> done
> 
> for ((i=0; i<${#parm[@]}; i+=2))
> do
>     declare var_${parm[i]}=${parm[i+1]}
> done
> 
> /opt/duc/bin/duc cgi -d "db/$var_db.db"`
> 
> in order to create links like `/cgi-bin/index.cgi?db=foobar-304`. Without the patch, the  links duc creates do not know which database to use. I might be doing something strange here, but my patch fixes it :)
> 
> thanks,
> -Christian
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/duc/pull/50#issuecomment-70251990

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by daduke** [comment]
Hi Ico,

you're right. We will change the way we generate the reports.

sorry for the noise.

-Christian

**Comment by zevv** [comment]
* On 2015-01-16 15:12:24 +0100, Christian Herzog wrote:
 
> you're right. We will change the way we generate the reports.
> 
> sorry for the noise.

No problem, you're welcome.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment]
Christian> you're right. We will change the way we generate the reports.

Christian> sorry for the noise.

No no no, don't be sorry!  I'm really happy you stepped up to make
this patch and propose it.  This is what duc in particular needs, and
open source in general needs, people willing to work to scratch and
itch.  

Ico didn't accept your patch, but he pointed out some issues with it
and what would need to be done to make it more rubust and acceptable.

I've been slowly... very slowly... working on adding in the -D option
to the cgi script so that it would present the DBs in a directory for
browsing, so you could select then the DB to view.  Look at my hacky
db_dir branch on there if you like for some initial steps I was
taking.

Having some means of index support would be awesome.   Ideally
something that's dynamic, but maybe your idea of an outside script to
build up the index page and the links on that page is what is needed
instead, with just a simple support for passing into the CGI script
the bare minimum.

John

**Comment by daduke** [comment]
hey John,

I'm not sorry for having brought it up, but Ico is completely right: my attempt was insecure and tried to 'fix' something at the wrong place. That said, the possibility to 'browse' a bunch of database files could be very interesting - right now we just let our generator script create an index page with links to several subdirectories. I could not try your db_dir branch (`cgi.c:381:2: error: implicit declaration of function ‘duc_pick_db_path’`), but I could imagine providing a db dir to DUC which then reads all db files in there, extracts the path and displays a list. Is that the idea?
I'm not sure of how much help I can be in that process as I'm really more of a Perl guy and my C is very rusty...

thanks,
-Christian

**Comment by zevv** [comment]
Hi Christian, John,

I think we're still not sure how to get to the One Final Proper CGI
solution. I feel that it is probably best to let Duc do the bare minimum
(just generate the graphs) and put all of the CGI logic into a separate
subproject, preferably not written in C but in a decent web scripting
language. All the messing with security and database files and all
should be left to the script layer, and not be part of Duc.

This also cleans some of the cruft out of the Duc core (javascript, css
files, popups, etc), so we can keep that lean and simple.

Calling Duc from the CGI could be done through the command line 'duc'
utility, or we could create a few bindings to export the Duc library
functions to the scripting layer.

I'm not sure what would be the proper scripting language though. I'm no
big fan of PHP or Perl, my Ruby and Python are rusty, and the one
scripting language I use on a daily basis (Lua) is not used on the web
at all. Any suggestions on this?


* On 2015-01-20 08:34:28 +0100, Christian Herzog wrote:
 
> hey John,
> 
> I'm not sorry for having brought it up, but Ico is completely right: my attempt was insecure and tried to 'fix' something at the wrong place. That said, the possibility to 'browse' a bunch of database files could be very interesting - right now we just let our generator script create an index page with links to several subdirectories. I could not try your db_dir branch (`cgi.c:381:2: error: implicit declaration of function ‘duc_pick_db_path’`), but I could imagine providing a db dir to DUC which then reads all db files in there, extracts the path and displays a list. Is that the idea?
> I'm not sure of how much help I can be in that process as I'm really more of a Perl guy and my C is very rusty...
> 
> thanks,
> -Christian
>  
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/duc/pull/50#issuecomment-70614873

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by l8gravely** [comment]
Christian> I'm not sorry for having brought it up, but Ico is
Christian> completely right: my attempt was insecure and tried to
Christian> 'fix' something at the wrong place. That said, the
Christian> possibility to 'browse' a bunch of database files could be
Christian> very interesting - right now we just let our generator
Christian> script create an index page with links to several
Christian> subdirectories. I could not try your db_dir branch
Christian> (cgi.c:381:2: error: implicit declaration of function
Christian> ‘duc_pick_db_path’), but I could imagine providing a db dir
Christian> to DUC which then reads all db files in there, extracts the
Christian> path and displays a list. Is that the idea?  I'm not sure
Christian> of how much help I can be in that process as I'm really
Christian> more of a Perl guy and my C is very rusty...

Christian, I just wanted to make sure you weren't going to drop out of
duc development, since in some places Ico's reply would have been
taken as "get out of here, you don't know what you're doing".  *grin*
Even though I know that's not what he meant.

I'm also much more of a perl programmer, and my C is rusty too, which
is why it's taking me so long to do this.  I keep thinking that maybe
the answer is to write duc in a form that it can be embedded into perl
or ruby as a C library that does what it needs quickly, but let's the
rest of the stuff happen in an easier to use language.

So I'll see if I can get my branch working better.  It's been a bit
painful, and I'm trying not to be too inefficient in my coding
practices.

John

**Comment by l8gravely** [comment]
zevv> I think we're still not sure how to get to the One Final Proper
zevv> CGI solution. I feel that it is probably best to let Duc do the
zevv> bare minimum (just generate the graphs) and put all of the CGI
zevv> logic into a separate subproject, preferably not written in C
zevv> but in a decent web scripting language. All the messing with
zevv> security and database files and all should be left to the script
zevv> layer, and not be part of Duc.

I think we're in agreement here then.  I've been fighting C string
handling code and just cursing all the time.  

zevv> This also cleans some of the cruft out of the Duc core
zevv> (javascript, css files, popups, etc), so we can keep that lean
zevv> and simple.

It would be nice to include this all into the project.  Certainly keep
the core in it's own directory structure, but move the CGI wrapper
stuff elsewhere? 

zevv> Calling Duc from the CGI could be done through the command line
zevv> 'duc' utility, or we could create a few bindings to export the
zevv> Duc library functions to the scripting layer.

That might be the best idea.  

zevv> I'm not sure what would be the proper scripting language
zevv> though. I'm no big fan of PHP or Perl, my Ruby and Python are
zevv> rusty, and the one scripting language I use on a daily basis
zevv> (Lua) is not used on the web at all. Any suggestions on this?

Well... since philesight was written in Ruby, maybe it makes sense to
use that language and leverage the existing work?  

One thought I've been thinking about is duc's concept of the top path
of a DB.  So we need an easy way to get the top level of the DB, then
a wrapper script can build an index page (dynamic or static) which
shows all the DBs you want and lets you navigate down into them.  And
of course 'duc info' does the right thing.

And then once you're in a DB, we need some way to navigate back to the
index, which is simple if we have a scripted CGI wrapper, or more
annoying and requiring a new command flag if duc itself has to handle
it.

John


zevv> * On 2015-01-20 08:34:28 +0100, Christian Herzog wrote:

>> hey John,
>> 
>> I'm not sorry for having brought it up, but Ico is completely right: my attempt was insecure and tried to 'fix' something at
zevv> the wrong place. That said, the possibility to 'browse' a bunch of database files could be very interesting - right now we just
zevv> let our generator script create an index page with links to several subdirectories. I could not try your db_dir branch
zevv> (`cgi.c:381:2: error: implicit declaration of function ‘duc_pick_db_path’`), but I could imagine providing a db dir to DUC which
zevv> then reads all db files in there, extracts the path and displays a list. Is that the idea?
>> I'm not sure of how much help I can be in that process as I'm really more of a Perl guy and my C is very rusty...
>> 
>> thanks,
>> -Christian
>> 
>> 
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/zevv/duc/pull/50#issuecomment-70614873

zevv> --
zevv> :wq
zevv> ^X^Cy^K^X^C^C^C^C

zevv> —
zevv> Reply to this email directly or view it on GitHub.*

**Comment by daduke** [comment]
hey John and Ico,

no offense taken. We're really grateful for this very nice philesight replacement (and we did have performance issues with philesight and can confirm that DUC is several times faster). Our scenario: we have > 100 group shares ranging from < 1 GiB to ~ 100 TiB. Each month we create report emails containing membership and space allocation 411 and a link to DUC graphs that we send to the group owners. We need quite a lot of Perl to do this anyway (for example we have to create .htaccess files to control access), so I don't mind creating the index pages on the way (once Ico shoved me in the right direction). So actually we're pretty happy already now, but of course library bindings would be an interesting option.

thanks,
-Christian

**Comment by zevv** [comment]
* On 2015-01-20 13:42:18 +0100, John wrote:
> 
> I think we're in agreement here then.  I've been fighting C string
> handling code and just cursing all the time.  

I've been doing just that for over 20 years :)

> zevv> This also cleans some of the cruft out of the Duc core
> zevv> (javascript, css files, popups, etc), so we can keep that lean
> zevv> and simple.
> 
> It would be nice to include this all into the project.  Certainly keep
> the core in it's own directory structure, but move the CGI wrapper
> stuff elsewhere? 

Something like that. It should be part of the project, but not of the
core C code.

> Well... since philesight was written in Ruby, maybe it makes sense to
> use that language and leverage the existing work?  

Fine with me. I don't think I will work much on the CGI code anyway, so
I'm a bit indifferent about the language. As long as the language is
widely deployed and portable it should be fine.

> One thought I've been thinking about is duc's concept of the top path
> of a DB.  So we need an easy way to get the top level of the DB, then
> a wrapper script can build an index page (dynamic or static) which
> shows all the DBs you want and lets you navigate down into them.  And
> of course 'duc info' does the right thing.

It would be nice to have the multiple-db-awareness built into duc
itself, so that a 'duc ls' or 'duc info' or 'duc graph' just does the
right thing. That's something all the tools can benefit from, not only
the CGI.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Pull request closed without merging**
