### PR TITLE
Update ducrc

### PR DESCRIPTION
**Pull request by jimsalterjrs**

### CODE REVIEW

**Comment by jimsalterjrs** [comment]
this got committed from an earlier version; newer version submitted in its place.

**Comment by zevv** [comment]
Thanks for that. I'm not merging as is, but I've updated the default ducrc with your comment, but with the 'database' option commented out by default.

**Comment by jimsalterjrs** [comment]
np. maybe consider doing some easily-discoverable in-place docs for setting this up with cron?  I'm VERY impressed with duc's scalability, which is why I was willing to poke through the source figuring out how to apply this globally in the first place. =)

btw, you still have some references to /etc/duc.conf in the NOTES, and AFAICT nothing actually reads /etc/duc.conf.  (Which to be honest would be my preferred nomenclature over /etc/ducrc, but whatevs.)

**Comment by zevv** [comment]
* On 2015-04-20 17:31:55 +0200, Jim Salter wrote:
 
> np. maybe consider doing some easily-discoverable in-place docs for
> setting this up with cron?  I'm VERY impressed with duc's scalability,
> which is why I was willing to poke through the source figuring out how
> to apply this globally in the first place. =)

Docs always need work :)

Cron is indeed a common use case that could use its own section in the
readme. 
 
> btw, you still have some references to /etc/duc.conf in the NOTES, and
> AFAICT nothing actually reads /etc/duc.conf.  

Thanks for spotting, will fix.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Pull request closed without merging**
